name: Metrics
on:
  schedule: [{cron: "0 8 * * *"}] # mise à jour tous les jours à 8h
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # Infos de base
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_order: base, languages, achievements, topics, music

          # Langages utilisés
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 1%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Succès (achievements)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          # Topics de repo
          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_limit: 12
          plugin_topics_sort: stars

          # Suivi des interactions
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Musique (Last.fm)
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_user: ton_nom_lastfm
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_music_played_at: yes

